# Site settings
title: Have we landed yet?
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  We're actually just wondering, if we landed yet.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
